#!/usr/bin/env python3
"""Generate the built-in 1-bpp SuperFb UI font from Microsoft YaHei.

The generated header is checked in so Linux/CI builds do not depend on a host
font or Pillow. Re-run this script only when the UI character set changes.
"""

from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "submodules/uefi/edk2/QcomModulePkg/Application/LinuxLoader/SuperFbFont.h"
FONT = Path(r"C:\Windows\Fonts\msyh.ttc")
HEIGHT = 48
STRIDE = 24  # two 4-bit alpha pixels per byte
ASCII = "".join(chr(i) for i in range(32, 127))
CJK = "启动菜单安卓工具进入程序选择器关机重新返回操作失败完成正在电源项控制模式重引导锁防回滚个表示默认音量移动键确认"
CHARS = ASCII + "".join(dict.fromkeys(CJK))


def render(ch: str):
    font = ImageFont.truetype(str(FONT), 39)
    probe = ImageDraw.Draw(Image.new("L", (1, 1), 0))
    advance = (max(14, min(36, round(probe.textlength(ch, font=font)) + 4))
               if ord(ch) < 128 else 48)
    image = Image.new("L", (48, HEIGHT), 0)
    draw = ImageDraw.Draw(image)
    box = draw.textbbox((0, 0), ch, font=font)
    width, height = box[2] - box[0], box[3] - box[1]
    x = (advance - width) // 2 - box[0]
    y = (HEIGHT - height) // 2 - box[1]
    draw.text((x, y), ch, fill=255, font=font)
    pixels = image.load()
    packed = []
    for row in range(HEIGHT):
        for byte_x in range(STRIDE):
            left = min(15, (pixels[byte_x * 2, row] + 8) // 17)
            right = min(15, (pixels[byte_x * 2 + 1, row] + 8) // 17)
            packed.append((left << 4) | right)
    return advance, packed


lines = [
    "/* Auto-generated by tools/gen_superfb_font.py. */",
    "#ifndef __SUPER_FB_FONT_H__",
    "#define __SUPER_FB_FONT_H__",
    "",
    "#define SFB_FONT_BITMAP_WIDTH  48",
    "#define SFB_FONT_HEIGHT        48",
    "#define SFB_FONT_STRIDE        24",
    "#define SFB_FONT_BYTES         (SFB_FONT_STRIDE * SFB_FONT_HEIGHT)",
    "",
    "typedef struct {",
    "  CHAR16  Codepoint;",
    "  UINT8   Advance;",
    "  UINT8   Bitmap[SFB_FONT_BYTES];",
    "} SFB_FONT_GLYPH;",
    "",
    "STATIC CONST SFB_FONT_GLYPH  mSfbFontGlyphs[] = {",
]

for ch in CHARS:
    advance, data = render(ch)
    lines.append(f"  {{ 0x{ord(ch):04X}, {advance}, {{")
    for offset in range(0, len(data), 16):
        chunk = ", ".join(f"0x{value:02X}" for value in data[offset:offset + 16])
        lines.append(f"    {chunk},")
    lines.append("  } },")

lines += ["};", "", "#endif", ""]
OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
print(f"generated {len(CHARS)} glyphs -> {OUT}")
