#!/usr/bin/env python3
"""Generate the built-in 4-bit-alpha Canoe UI font from Microsoft YaHei.

The generated header is checked in so Linux/CI builds do not depend on a host
font or Pillow. Re-run this script only when the UI character set changes.
"""

from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "submodules/uefi/edk2/QcomModulePkg/Application/LinuxLoader/SuperFbFont.h"
FONT = Path(r"C:\Windows\Fonts\msyh.ttc")
HEIGHT = 72
STRIDE = 36  # two 4-bit alpha pixels per byte
SUPERSAMPLE = 3
ASCII = "".join(chr(i) for i in range(32, 127))
CJK = "启动菜单安卓工具进入程序选择器关机重新返回操作失败完成正在电源项控制模式重引导锁防回滚个表示默认音量移动键确认设置配色主题蓝紫绿橙简易密码关闭保存已更改输入错误重试数字位当前下一页退出解锁：不第定度方请顺行按备到的读法访服该和候加件禁就卷开览临浏录目内驱取稍时是所添未文问无务绪言要应用语载找中准足"
CJK += "初打管后化继接理连脑使始态续状"
UI_SOURCES = [
    ROOT / "submodules/uefi/edk2/QcomModulePkg/Application/LinuxLoader/SuperFbMenu.c",
    ROOT / "submodules/uefi/edk2/QcomModulePkg/Application/LinuxLoader/SuperFbEntries.c",
    ROOT / "submodules/uefi/edk2/AndroidToolsPkg/Library/AndroidToolsUi/AndroidToolsUi.c",
    ROOT / "submodules/uefi/edk2/AndroidToolsPkg/Application/ArbTools/ArbTools.c",
    ROOT / "submodules/uefi/edk2/AndroidToolsPkg/Application/BLTools/BLTools.c",
    ROOT / "submodules/uefi/edk2/AndroidToolsPkg/Application/MiniGames/MiniGames.c",
]
for source in UI_SOURCES:
    if source.exists():
        CJK += "".join(ch for ch in source.read_text(encoding="utf-8")
                       if ord(ch) >= 128)
CHARS = ASCII + "".join(dict.fromkeys(CJK))


def render(ch: str):
    logical_size = 58
    font = ImageFont.truetype(str(FONT), logical_size)
    probe = ImageDraw.Draw(Image.new("L", (1, 1), 0))
    advance = (max(20, min(56, round(probe.textlength(ch, font=font)) + 6))
               if ord(ch) < 128 else HEIGHT)

    # Rasterize at 3x and reduce with Lanczos. The firmware can then resize
    # this clean master using bilinear alpha sampling without the stair-step
    # edges produced by the old 48px nearest-neighbour path.
    high = Image.new("L", (HEIGHT * SUPERSAMPLE, HEIGHT * SUPERSAMPLE), 0)
    draw = ImageDraw.Draw(high)
    high_font = ImageFont.truetype(str(FONT), logical_size * SUPERSAMPLE)
    # Keep every glyph on one font baseline. Centering each outline separately
    # makes punctuation float vertically and gives Latin text uneven spacing.
    box = draw.textbbox((0, 0), ch, font=high_font, anchor="ls")
    x = 3 * 3 - min(0, box[0])
    baseline = 62 * SUPERSAMPLE
    draw.text((x, baseline), ch, fill=255, font=high_font, anchor="ls")
    image = high.resize((HEIGHT, HEIGHT), Image.Resampling.LANCZOS)
    pixels = image.load()
    packed = []
    for row in range(HEIGHT):
        for byte_x in range(STRIDE):
            left = min(15, (pixels[byte_x * 2, row] + 8) // 17)
            right = min(15, (pixels[byte_x * 2 + 1, row] + 8) // 17)
            packed.append((left << 4) | right)
    return advance, packed


lines = [
    "/* Auto-generated by tools/gen_superfb_font.py. */",
    "#ifndef __SUPER_FB_FONT_H__",
    "#define __SUPER_FB_FONT_H__",
    "",
    "#define SFB_FONT_BITMAP_WIDTH  72",
    "#define SFB_FONT_HEIGHT        72",
    "#define SFB_FONT_STRIDE        36",
    "#define SFB_FONT_BYTES         (SFB_FONT_STRIDE * SFB_FONT_HEIGHT)",
    "",
    "typedef struct {",
    "  CHAR16  Codepoint;",
    "  UINT8   Advance;",
    "  UINT8   Bitmap[SFB_FONT_BYTES];",
    "} SFB_FONT_GLYPH;",
    "",
    "STATIC CONST SFB_FONT_GLYPH  mSfbFontGlyphs[] = {",
]

for ch in CHARS:
    advance, data = render(ch)
    lines.append(f"  {{ 0x{ord(ch):04X}, {advance}, {{")
    for offset in range(0, len(data), 16):
        chunk = ", ".join(f"0x{value:02X}" for value in data[offset:offset + 16])
        lines.append(f"    {chunk},")
    lines.append("  } },")

lines += ["};", "", "#endif", ""]
OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
print(f"generated {len(CHARS)} glyphs -> {OUT}")
